### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by pullobi** [yurihikari/garuda-sway-config#2]
i made some fixes you can check it out in github.com/pullobi/hyprland.config
i made rofi work,but cava is not wirking for me.
and i added a neovim theme

**Comment by yurihikari** [comment]
Hello!
May I ask for some more details? 
Was rofi not working on hyprland or sway (or both) ?
Cava should work only on sway. I didn't configure it for hyprland since I use mako notifications instead.
Feel free to make a pull requests for said fixes, so I can take a look and also make this repo better :smiley:

**Comment by pullobi** [comment]
I didn't test anything on sway, just some errors on hyprland, catppuccin-mocha didn't exist, found it somewhere and fixed it.

**Comment by yurihikari** [comment]
Sorry for the **very** late reply, most of the fixes should have been made in my repo, probably some small breaking changes from hyprland, so I had to comment/remove some lines.
Also removed the catppuccin-mocha import from rofi, since I don't use that theme and I forgot to remove the line when i was ricing.
Unless you have other issues, I'll close this issue. Thanks for your help.
